// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/data/fighters/fighters.js";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/Fighter.tsx";
import * as $$1 from "./islands/Fighters.tsx";

const manifest = {
  routes: {
    "./routes/api/data/fighters/fighters.js": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/Fighter.tsx": $$0,
    "./islands/Fighters.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
