// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_data_fighters_fighters from "./routes/api/data/fighters/fighters.js";
import * as $index from "./routes/index.tsx";
import * as $Fight from "./islands/Fight.tsx";
import * as $Fighter from "./islands/Fighter.tsx";
import * as $Modal from "./islands/Modal.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/data/fighters/fighters.js": $api_data_fighters_fighters,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Fight.tsx": $Fight,
    "./islands/Fighter.tsx": $Fighter,
    "./islands/Modal.tsx": $Modal,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
